# Generated by Django 2.1.5 on 2025-03-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageflip', '0002_auto_20250306_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgenrecategory',
            options={'verbose_name_plural': 'Sub-Genre Categories'},
        ),
    ]
