# Generated by Django 2.1.5 on 2025-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageflip', '0005_auto_20250314_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenrecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
