# Generated by Django 2.1.5 on 2025-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageflip', '0006_subgenrecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
